### PR TITLE
+ Mathieu GP

### PR DESCRIPTION
**Pull request by mathieugp**
Ma fiche.

### CODE REVIEW

**Comment by mathieugp** [comment]
@Carms-dev For some reason I do not appear as a new team member in the deployment preview above. What did I do wrong?

**Comment by Carms-dev** [comment]
> @Carms-dev For some reason I do not appear as a new team member in the deployment preview above. What did I do wrong?

Hi Mattieu, did you add this image -> 003_mathieu_gauthier_pilote.jpg <- to src/assets/images/portraits directory?

**Comment by mathieugp** [comment]
> Hi @mathieugp, did you add this image -> 003_mathieu_gauthier_pilote.jpg <- to src/assets/images/portraits directory?

Now I have. :-)

**Comment by Carms-dev** [comment]
> > Hi @mathieugp, did you add this image -> 003_mathieu_gauthier_pilote.jpg <- to src/assets/images/portraits directory?
> 
> @Carms-dev : Now I have. :-)

Great!  Deploy looks good.  If you want your bio to appear in french as well, you can add the corresponding string -> locales/fr/team.fr.json

**Review by Carms-dev — APPROVED** [review]

**Comment by mathieugp** [comment]
@Carms-dev : Translation added. Good to merge! :-)

**Pull request merged**
