### PR TITLE
[Add] Landing Page

### PR DESCRIPTION
**Pull request by Carms-dev**
- Setup global styles, typeface: Young Serif pair with Share Tech), color scheme, site border
- Header
- Hero + Logo Garden
Screenshot from 2021-03-28 14-27-54

### CODE REVIEW

**Comment by Carms-dev** [comment]
TODO:

- [ ] Team Section
- [ ] Contact Section
- [ ] Wire contact form (Netlify?)
- [ ] Fix Scroll Snap
- [ ] Optimize Background images
- [ ] Wire Page 2 / Agreement in PDF?
- [ ] Improve Language Switcher

**Comment by rngadam** [comment]
@Carms-dev 

Very nice, I like the style so far! 

I think I'd comment out the quantity of talents (3 bunkers, 50+ talents) for now and list the team with pics instead. 

As we build the rooster of employees and collaborators (maybe visually distinguish both) and get a significant number of collaborators in Canada we can put those back. For now, we focus on highlighting the members of the team physically here.

**Comment by Carms-dev** [comment]
> I think I'd comment out the quantity of talents (3 bunkers, 50+ talents) for now and list the team with pics instead.

Can you expand on _list the team with pics_?  Something like this?  
Screenshot from 2021-03-31 18-26-46

I will be adding the team members in the _Consult Your Tech Lead_ section.  We can do the stacked avatar above, or a call to action button, or leave it blank.  Let me know!

Also can you send me Élic's pic?  and others that you'd like to include?

**Comment by Carms-dev** [comment]
@rngadam 

Added Team Section

Screenshot from 2021-04-01 01-51-24

**Comment by rngadam** [comment]
The stacked avatar is a good idea, I wasn't thinking of that but good suggestion.

here's the team as it is now from which I think you can get the profile pictures:

* https://www.linkedin.com/in/rngadam/
* https://www.linkedin.com/in/elicng/
* https://www.linkedin.com/in/jvtrudel/
* https://www.linkedin.com/in/andrea-obrien-a20b2450/ (I'm asking her to update her profile)
* https://www.linkedin.com/in/manuelviens/

expected to add quickly more employees and more freelancers as we grow to the community. so it's important that whatever you build be easy to edit and customise. 

I see you've got it as part of the team.js file which is already pretty easy to maintain, but I'd go a bit further and turn it into a team.json file that you fetch at runtime.

**Comment by Carms-dev** [comment]
@rngadam 

> here's the team as it is now from which I think you can get the profile pictures:

Linkedin resizes profile pic.  It's good enough for the stacked avatar, but not in the Team Section.  When you have a chance, Can you provide the original for elic / andrea / manuel?

Thanks!

**Comment by rngadam** [comment]
OK, sent email to request higher rez pics.

Once you get this pull request in, I suggest we break down the big main issue into smaller, more focused linked issues and have one pull request per issue so we can incrementally build the site.

**Comment by Carms-dev** [comment]
- [ ] Fix Android keyboard vh distortion

**Comment by Carms-dev** [comment]
Netlify - https://coderbunker.netlify.app/

**Comment by Carms-dev** [comment]
Hey @rngadam - the broad stokes of the landing page is done🔥  I want to loop you or others in for the following

- [ ] FR translation
- [ ] Add the remaining profile & picture & profile
- [ ] Replace the placeholder pdf when the Retainer Agreement PDF is ready
- [ ] Update contact information
- [ ] Custom domain set up on [Netlify](coderbunker.netlify.app)

**Comment by rngadam** [comment]
* look at validators online to validate the page
* document the deployment steps and structure of code
* deploy to coderbunker.ca (access to Google Domains)
* Correct address:

Coderbunker Inc.
2-227 St-Paul
Quebec, QC G1K 3W3
+1 438-530-7111
* production deployment from main and branches to staging

**Pull request merged**
